config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :templates, shallow: true do
    resources :users, param: :slug
  end

  get '/:slug', to: 'users#edit', as: :slug

  root "templates#index"
end

app/views/templates/_form.html.erb
<%= form_with(model: template) do |form| %>
  <% if template.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
        <% template.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/templates/_template.html.erb
<div id="<%= dom_id template %>">
  <p>
    <strong>Name:</strong>
    <%= template.name %>
  </p>

</div>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render "form", template: @template %>

<br>

<div>
  <%= link_to "Show this template", @template %> |
  <%= link_to "Back to templates", templates_path %>
</div>

app/views/templates/index.html.erb
<div class="overflow-hidden bg-white shadow sm:rounded-lg w-full">
  <div class="flex items-center justify-between px-4 py-5 sm:px-6">
    <h3 class="text-lg font-medium leading-6 text-gray-900">Plantillas</h3>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <% @templates.each do |template| %>
        <div class="<%= cycle("bg-gray-50", "bg-white") -%> px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <%= link_to template_users_path template do %>
            <dt class="text-sm font-medium text-indigo-600 hover:text-indigo-500">
              <%= template.name %>
            </dt>
          <% end %>
        </div>
      <% end %>
    </dl>
  </div>
</div>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render "form", template: @template %>

<br>

<div>
  <%= link_to "Back to templates", templates_path %>
</div>

app/views/templates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @template %>

<div>
  <%= link_to "Edit this template", edit_template_path(@template) %> |
  <%= link_to "Back to templates", templates_path %>

  <%= button_to "Destroy this template", @template, method: :delete %>
</div>