config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :templates, shallow: true do
    resources :users, param: :slug
  end

  get '/:slug', to: 'users#edit', as: :slug

  root "templates#index"
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :template

  has_many :records, dependent: :destroy
  accepts_nested_attributes_for :records

  before_create :set_defaults
  after_create :create_records

  def to_param
    slug
  end

  private

    def set_defaults
      self.slug = SecureRandom.urlsafe_base64(6)
    end

    def create_records
      template.record_types.each do |record_type|
        records.create! record_type:
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!, except: %i[ show edit update ]
  before_action :set_template, only: %i[ index new create ]
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = @template.users.order :name
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = @template.users.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = @template.users.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_template
      @template = current_admin.templates.find(params[:template_id])
    end

    def set_user
      @user = User.find_by(slug: params[:slug])
    end

    def user_params
      params.require(:user).permit(:name, :email, records_attributes: [ :id, :value, :file ])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: [@template, user]) do |form| %>
  <div class="overflow-hidden shadow sm:rounded-md">
    <div class="bg-white px-4 py-5 sm:p-6">
      <div class="grid grid-cols-6 gap-6">
        <div class="col-span-12 sm:col-span-12">
          <label for="first-name" class="block text-sm font-medium text-gray-700">Nombre y Apellidos</label>
          <%= form.text_field :name, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
        </div>

        <div class="col-span-12">
          <label for="first-name" class="block text-sm font-medium text-gray-700">Email</label>
          <%= form.email_field :email, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
        </div>

        <%= form.fields_for :records do |record_field| %>
          <%= render "records/form_#{record_field.object.input_type}", record_field: %>
        <% end %>
      </div>
    </div>
    <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
      <%= form.submit "Guardar", class: "inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
<% end %>




  

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<div>
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="md:col-span-1">
      <div class="px-4 sm:px-0">
        <h3 class="text-lg font-medium leading-6 text-gray-900"><%= @user.template.name %></h3>
        <p class="mt-1 text-sm text-gray-600">Rellena cada uno de los campos y adjunta los documentos solicitados.</p>
      </div>
    </div>
    <div class="mt-5 md:col-span-2 md:mt-0">
      <%= render "form", user: @user %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="overflow-hidden bg-white shadow sm:rounded-lg w-full">
  <div class="flex items-center justify-between px-4 py-5 sm:px-6">
    <h3 class="text-lg font-medium leading-6 text-gray-900"><%= @template.name %></h3>
    <%= link_to "Nuevo Usuario", new_template_user_path(@template), class: "ml-8 inline-flex items-center justify-center whitespace-nowrap rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700" %>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <% @users.each do |user| %>
        <div class="<%= cycle("bg-gray-50", "bg-white") -%> px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <%= link_to user_path user do %>
            <dt class="text-sm font-medium text-indigo-600 hover:text-indigo-500"><%= user.name %></dt>
          <% end %>
        </div>
      <% end %>
    </dl>
  </div>
</div>

app/views/users/new.html.erb
<div>
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="md:col-span-1">
      <div class="px-4 sm:px-0">
        <h3 class="text-lg font-medium leading-6 text-gray-900">Nuevo Usuario</h3>
        <p class="mt-1 text-sm text-gray-600">Rellena cada uno de los campos para crear un nuevo usuario</p>
      </div>
    </div>
    <div class="mt-5 md:col-span-2 md:mt-0">
      <%= render "form", user: @user %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="overflow-hidden bg-white shadow sm:rounded-lg w-full">
  <div class="flex items-center justify-between px-4 py-5 sm:px-6">
    <h3 class="text-lg font-medium leading-6 text-gray-900"><%= @user.template.name %></h3>
    <%= link_to "Editar datos", edit_user_path(@user), class: "ml-8 inline-flex items-center justify-center whitespace-nowrap rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700" %>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Link de usuario</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0" data-controller="clipboard">
          <span data-clipboard-target="source"><%= slug_url @user.slug %></span>
          <a href="#" data-action="clipboard#copy"
                      class="font-medium text-indigo-600 hover:text-indigo-500 px-3">
            copiar
          </a>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Nombres y Apellidos</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= @user.name %></dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Email</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= @user.email %></dd>
      </div>
      <% @user.records.each do |record| %>
        <%= render "records/#{record.input_type}", record: %>
      <% end %>
    </dl>
  </div>
</div>